/**
 * SIMULATED DATA — replace with real Supabase `properties`/`property_media`
 * queries once Property Management (Phase 5) exists. `properties.owner_id`
 * has a hard FK to a real agent profile, so this can't be seeded as real
 * rows without first building Agent CRM — kept as a typed, isolated mock
 * dataset instead, matching the pattern already used by
 * components/landing/FeaturedListings.tsx.
 */
import type { Property } from "@/types/property";

export interface MockProperty extends Property {
  description: string;
  amenities: string[];
  landlordName: string;
  landlordAvatar: string;
  baseSafetyScore: number;
  baseCommuteMinutes: number;
  createdAt: string;
  /** Real listings only — the owning agent's profile id, used to start a conversation. */
  ownerId?: string;
}

export const mockProperties: MockProperty[] = [
  {
    id: "prop-101",
    title: "Modern 2-Bedroom Apartment",
    location: "Accra, Ghana",
    neighborhood: "East Legon",
    price: 2800,
    priceUnit: "month",
    currency: "GHS",
    bedrooms: 2,
    bathrooms: 2,
    area: 95,
    imageUrl: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=900&q=80",
    tags: ["Furnished", "Air Conditioned", "Parking", "Security"],
    isVerified: true,
    isAIMatched: true,
    agentName: "Kwame Mensah",
    agentAvatar: "https://i.pravatar.cc/40?img=3",
    description:
      "A bright, modern 2-bedroom apartment in the heart of East Legon, minutes from restaurants and shopping. Fully furnished with air conditioning throughout and a dedicated parking space.",
    amenities: ["Air conditioning", "24/7 security", "Parking", "Fitted kitchen", "Furnished"],
    landlordName: "Kwame Mensah",
    landlordAvatar: "https://i.pravatar.cc/40?img=3",
    baseSafetyScore: 88,
    baseCommuteMinutes: 18,
    createdAt: "2026-06-28T09:00:00Z",
  },
  {
    id: "prop-102",
    title: "Executive Studio",
    location: "Accra, Ghana",
    neighborhood: "Airport Residential",
    price: 1900,
    priceUnit: "month",
    currency: "GHS",
    bedrooms: 1,
    bathrooms: 1,
    area: 58,
    imageUrl: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=900&q=80",
    tags: ["Furnished", "Fiber Internet", "Gym"],
    isVerified: true,
    isAIMatched: false,
    agentName: "Abena Boateng",
    agentAvatar: "https://i.pravatar.cc/40?img=5",
    description:
      "Compact, stylish studio ideal for remote work, with fast fiber internet and access to a shared gym. Walking distance to cafes in Airport Residential.",
    amenities: ["Fiber internet", "Gym access", "Furnished", "Elevator"],
    landlordName: "Abena Boateng",
    landlordAvatar: "https://i.pravatar.cc/40?img=5",
    baseSafetyScore: 82,
    baseCommuteMinutes: 22,
    createdAt: "2026-06-15T09:00:00Z",
  },
  {
    id: "prop-103",
    title: "Spacious Family House",
    location: "Accra, Ghana",
    neighborhood: "Cantonments",
    price: 6500,
    priceUnit: "month",
    currency: "GHS",
    bedrooms: 4,
    bathrooms: 3,
    area: 280,
    imageUrl: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=900&q=80",
    tags: ["Garden", "Pool", "Security"],
    isVerified: true,
    isAIMatched: true,
    agentName: "Kofi Asante",
    agentAvatar: "https://i.pravatar.cc/40?img=8",
    description:
      "A spacious family home in Cantonments with a private garden and pool, gated with round-the-clock security. Close to international schools.",
    amenities: ["Private pool", "Garden", "24/7 security", "Staff quarters", "Generator backup"],
    landlordName: "Kofi Asante",
    landlordAvatar: "https://i.pravatar.cc/40?img=8",
    baseSafetyScore: 93,
    baseCommuteMinutes: 25,
    createdAt: "2026-05-30T09:00:00Z",
  },
  {
    id: "prop-104",
    title: "Cozy Student Studio",
    location: "Accra, Ghana",
    neighborhood: "Legon",
    price: 1200,
    priceUnit: "month",
    currency: "GHS",
    bedrooms: 1,
    bathrooms: 1,
    area: 32,
    imageUrl: "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=900&q=80",
    tags: ["Furnished", "Near Campus"],
    isVerified: true,
    isAIMatched: false,
    agentName: "Ama Owusu",
    agentAvatar: "https://i.pravatar.cc/40?img=12",
    description:
      "Affordable, furnished studio a short walk from the University of Ghana campus — ideal for students who want a quiet place to focus.",
    amenities: ["Furnished", "Study desk", "Shared laundry", "Water storage backup"],
    landlordName: "Ama Owusu",
    landlordAvatar: "https://i.pravatar.cc/40?img=12",
    baseSafetyScore: 76,
    baseCommuteMinutes: 8,
    createdAt: "2026-06-30T09:00:00Z",
  },
  {
    id: "prop-105",
    title: "Modern 2-Bedroom Near UPSA",
    location: "Accra, Ghana",
    neighborhood: "Madina",
    price: 1500,
    priceUnit: "month",
    currency: "GHS",
    bedrooms: 2,
    bathrooms: 1,
    area: 68,
    imageUrl: "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=900&q=80",
    tags: ["Security", "Water Storage"],
    isVerified: true,
    isAIMatched: false,
    agentName: "Yaw Darko",
    agentAvatar: "https://i.pravatar.cc/40?img=15",
    description:
      "Well-maintained 2-bedroom apartment a short drive from UPSA, in a gated compound with reliable water storage and a night watchman.",
    amenities: ["Gated compound", "Water storage", "Night security"],
    landlordName: "Yaw Darko",
    landlordAvatar: "https://i.pravatar.cc/40?img=15",
    baseSafetyScore: 79,
    baseCommuteMinutes: 12,
    createdAt: "2026-06-10T09:00:00Z",
  },
  {
    id: "prop-106",
    title: "Family Home Near Spintex",
    location: "Accra, Ghana",
    neighborhood: "Spintex",
    price: 3200,
    priceUnit: "month",
    currency: "GHS",
    bedrooms: 3,
    bathrooms: 2,
    area: 140,
    imageUrl: "https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=900&q=80",
    tags: ["Furnished", "Parking", "Security"],
    isVerified: true,
    isAIMatched: false,
    agentName: "Efua Mensah",
    agentAvatar: "https://i.pravatar.cc/40?img=20",
    description:
      "Comfortable 3-bedroom home near the Spintex road, close to shopping malls and schools, with covered parking for two vehicles.",
    amenities: ["Furnished", "Covered parking", "Security", "Backyard"],
    landlordName: "Efua Mensah",
    landlordAvatar: "https://i.pravatar.cc/40?img=20",
    baseSafetyScore: 84,
    baseCommuteMinutes: 20,
    createdAt: "2026-06-22T09:00:00Z",
  },
  {
    id: "prop-107",
    title: "Furnished Flat Near Airport",
    location: "Accra, Ghana",
    neighborhood: "Airport Residential",
    price: 2600,
    priceUnit: "month",
    currency: "GHS",
    bedrooms: 2,
    bathrooms: 2,
    area: 88,
    imageUrl: "https://images.unsplash.com/photo-1484154218962-a197022b5858?w=900&q=80",
    tags: ["Furnished", "Air Conditioned", "Gym"],
    isVerified: true,
    isAIMatched: true,
    agentName: "Nana Adjei",
    agentAvatar: "https://i.pravatar.cc/40?img=25",
    description:
      "Fully furnished 2-bedroom flat close to Kotoka International Airport, ideal for frequent travelers, with access to a shared gym and pool.",
    amenities: ["Furnished", "Air conditioning", "Gym access", "Pool access"],
    landlordName: "Nana Adjei",
    landlordAvatar: "https://i.pravatar.cc/40?img=25",
    baseSafetyScore: 90,
    baseCommuteMinutes: 15,
    createdAt: "2026-07-01T09:00:00Z",
  },
];
